# Deep Fund Configuration
exp_name: "llama-3.1-70b-buffett"

# Trading settings
cashflow: 100000
tickers:
  - AAPL
  - AXP
  - BAC
  - KO
  - CVX

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - technical
  - insider
  - company_news
  - policy

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "Fireworks" 
  model: "accounts/fireworks/models/llama-v3p1-70b-instruct"