# Deep Fund Configuration
exp_name: "firework-test-3"

# Trading settings
cashflow: 100000
tickers:
  - TSLA
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - company_news
  - technical


# YiZhan is a unified API proxy for all LLM models
llm:
  provider: "Fireworks" 
  model: "accounts/fireworks/models/mixtral-8x22b-instruct" 

