# Deep Fund Configuration
exp_name: "ollama-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental

# Ollama is a community-driven LLM provider
# Model list can be found via `ollama list`
llm:
  provider: "Ollama" 
  model: "llama3.1:8b" 

