# Deep Fund Configuration
exp_name: "ollama-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  - insider

# YiZhan is a unified API proxy for all LLM models
llm:
  provider: "Ollama" 
  model: "llama3.1:8b" 

