# Deep Fund Configuration

# Trading settings
ticker_scope: "test"   # References a scope in tickers.json

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  # - technical
  # - insider
  - news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "DeepSeek" 
  model: "deepseek-chat" # DeepSeek-V3

