# Deep Fund Configuration
# Trading settings
tickers:
  - MSFT
  - NVDA
  # - TSLA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  # - technical
  # - insider
  - news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "DeepSeek" 
  model: "deepseek-chat" # DeepSeek-V3

