# Deep Fund Configuration

# Trading settings
trading:
  start_date: "2025-01-01"  # Optional, defaults to 3 months before end_date
  end_date: "2025-03-01"    # Optional, defaults to today
  ticker_scope: "test"   # References a scope in tickers.json

# Workflow settings
workflow:
  image_path: "image/workflow.png" # relative to main.py
  analysts:
    - fundamental
    - risk
    # - technical
    # - sentiment

# LLM model settings
llm:
  provider: "Ollama"  # OpenAI, Groq, Anthropic, Deepseek, Ollama
  model: "deepseek-r1:latest"
  temperature: 0.5

