# Deep Fund Configuration

# Trading settings
trading:
  start_date: "2025-01-01"  # Optional, defaults to 3 months before end_date
  end_date: "2025-03-01"    # Optional, defaults to today
  ticker_scope: "test"   # References a scope in tickers.json

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  - technical
  - insider
  - news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "Ollama"  # OpenAI, Groq, Anthropic, Deepseek, Ollama
  model: "llama3.1:8b"
  temperature: 0.5

