# Deep Fund Configuration
exp_name: "dev"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  - company_news
  - technical
  - insider

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "DeepSeek" 
  model: "deepseek-chat" # DeepSeek-V3

