# Deep Fund Configuration

# Portfolio settings
portfolio:
  initial_cash: 100000.0
  margin_requirement: 0.0

# Trading settings
trading:
  start_date: "2025-01-01"  # Optional, defaults to 3 months before end_date
  end_date: "2025-03-01"    # Optional, defaults to today
  ticker_scope: "test"   # References a scope in tickers.json

# Analyst settings (specify which analysts to use)
analysts:
  # - technical_analyst
  - fundamentals_analyst
  # - sentiment_analyst
  # - valuation_analyst

# LLM model settings
llm:
  provider: "Custom"  # OpenAI, Groq, Anthropic, Ollama, Custom
  model: "gpt-4o-mini"
  # Custom API endpoint settings (used when provider is "Custom")
  custom_endpoint:
    url: "https://vip.yi-zhan.top/v1"
    api_key_env_var: "YI_ZHAN_API_KEY"
    headers:
      Content-Type: "application/json"

# Logging settings
log:
  log_dir: "logs"
  log_level: "INFO"
  file_prefix: "deep_fund"